### ISSUE TITLE
Update dependency list in the docs

### ISSUE THREAD

**Issue by dstansby** [EnsembleGovServices/kamodo-core#19]
[JOSS requirement]
The list of requirements in the docs (https://ccmc.gsfc.nasa.gov/Kamodo/#requirements) is not the same as the requirements in `setup.cfg` (https://github.com/EnsembleGovServices/kamodo-core/blob/2f80f79da1ee9b6c703f2c16eee66e7100311535/setup.cfg#L22). The list in the docs should be updated to reflect the requirements in `setup.cfg`.

**Comment by asher-pembroke** [comment]
Our github pages versions linked from the repo now matches setup.cfg https://ensemblegovservices.github.io/kamodo-core/#requirements We'll ask the ccmc to redirect the outdated documentation site here.
