### ISSUE TITLE
Add contribution/reporting/support guidelines

### ISSUE THREAD

**Issue by dstansby** [EnsembleGovServices/kamodo-core#20]
[JOSS requirement]
One of the requirements for JOSS is:
> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

As far as I can tell there are no clear guidelines, for this, or they are hard to discover. These guidelines should be added in a prominent position in the docs.

**Comment by asher-pembroke** [comment]
We've added a CONTRIBUTING.md file to our docs/ available in the documentation site https://ensemblegovservices.github.io/kamodo-core/CONTRIBUTING/
