### ISSUE TITLE
Describe how to run (or automate) the test suite

### ISSUE THREAD

**Issue by dstansby** [EnsembleGovServices/kamodo-core#21]
[JOSS requirement]
It looks like there are a series of tests in the repository which is 👍 . These don't seem to be automatically run, and there aren't any instructions in the docs on how to run them. Either:
- Automated runs of the tests should be set up using continuous integration
- Clear steps on how a user can run the test suite should be added to the documentation

**Comment by asher-pembroke** [comment]
This is now in the master branch README here https://github.com/EnsembleGovServices/kamodo-core#test-suite
