### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by dstansby** [EnsembleGovServices/kamodo-core#28]
[JOSS requirement]
The online documentation has a really good guide to get users up and running with kamodo. As far as I can tell it doesn't have any API documentation however, ie. a list of all the functions/classes that are provided, along with descriptions of what they do and their inputs/outputs.

**Comment by asher-pembroke** [comment]
We've added an [API page](https://ensemblegovservices.github.io/kamodo-core/API/) to the documentation site. The documentation is not complete, but it's a start.

**Comment by asher-pembroke** [comment]
This issue has been resolved in and is in the master branch.

**Comment by dstansby** [comment]
Could you re-open this? The new API documentation seems to be here: https://ensemblegovservices.github.io/kamodo-core/API/#plotting (let me know if I'm in the wrong place!), but it seems incomplete. In particular:

- There aren't descriptions and types documented for all the input arguments for all methods/functions
- There aren't descriptions and types documented for all the returned values for all methods/functions

**Comment by dstansby** [comment]
To automatically generate API documentation from docstrings, I can recommend https://sphinx-automodapi.readthedocs.io/en/latest/index.html

**Comment by asher-pembroke** [comment]
We've made some significant improvements to our api recently. Closing for now.
