### ISSUE TITLE
Incorrect axis labels for multi-variable plotting in 1D

### ISSUE THREAD

**Issue by rebeccaringuette** [EnsembleGovServices/kamodo-core#35]
## Describe the bug
When plotting multiple one-dimensional variables (e.g. three time series), the plot title and the vertical axis reflect only the last variable included.
![image](https://user-images.githubusercontent.com/49281118/153310720-f38b66d5-a311-4fe9-b2b6-5b6d07a510e0.png)

### Registration error
The error occurred at the end of the linked notebook: https://drive.google.com/file/d/1JQnyg9Qvvnqo1FNzWNgk6fuoxArloCK2/view?usp=sharing

Code excerpt: (results is a dictionary of time-series arrays)
```python
#This block shows how to functionalize two time series arrays that depend on datetime objects
#Basing these time series arrays on datetime objects instead of UTC timestamps makes the plots easier to understand
#scipy cannot handle arrays of datetime objects, so we have to jump through some hoops

#import statements
from kamodo import Kamodo, kamodofy
from scipy.interpolate import interp1d
import numpy as np
from datetime import datetime, timezone

#define a function to convert utc timestamps to date-time objects
@np.vectorize
def ts_to_datetime(time_val):
    return datetime.utcfromtimestamp(time_val).replace(tzinfo=timezone.utc)
#perform the conversion on the array of UTC timestamps
time_date = ts_to_datetime(results['utc_time'])  

#define a function to convert back to utc timestamps
#this will be used in the function definitions for Kamodo
@np.vectorize
def datetime_to_utcts(date_time):
    return datetime.timestamp(date_time)

#define an interpolator for each given time series array
#change the chosen keys to match the requested variables OR replace results[key] with your own numpy array
interp_rho = interp1d(results['utc_time'], results['rho'], bounds_error=False, fill_value=np.NaN) 
interp_Tn = interp1d(results['utc_time'], results['T_n'], bounds_error=False, fill_value=np.NaN)

#functionalize each time series array
@kamodofy(units='K', data=results['T_n'])#, arg_units={'time':'s'})  #units from printed output of block 10
def T_n_func(time = time_date):  #function depends on array of datetime objects
    utc_ts = datetime_to_utcts(time)  #convert the given datetime objects to UTC timestamps
    return interp_Tn(utc_ts)     #return the scipy interpolator
    
@kamodofy(units='g/cm**3', data=results['rho'])#, arg_units={'time':'s'})  #units from printed output of block 10
def rho_func(time = time_date):  #function depends on array of datetime objects
    utc_ts = datetime_to_utcts(time)  #convert the given datetime objects to UTC timestamps
    return interp_rho(utc_ts)   #return the scipy interpolator

#define a Kamodo object to include all the desired functions
#Each variable in the Kamodo object must have a unique name
kamodo_object = Kamodo(T_n=T_n_func, rho=rho_func) 
kamodo_object['rho_2[mg/km**3]'] = 'rho'
kamodo_object.plot('T_n', 'rho_2', 'rho')  
```

**Comment by asher-pembroke** [comment]
Plotly has the ability to use [Multiple Axes
](https://plotly.com/python/multiple-axes/) for the same plot. Is that the requested fix intended here, where each unique unit goes on a separate axis?

**Comment by rebeccaringuette** [comment]
Possibly. That could get messy with 3+ units on the same plot, but I would
think it's unusual for someone to request a plot with more than 3 unique
units. However, I have seen plots with 4 of these. Maybe limit it to 4
unique units (likely two on each vertical axis)?

Rebecca Ringuette

**Comment by asher-pembroke** [comment]
If it starts to look messy they can always make a separate plot. That way we don't have to decide for them.

**Comment by rebeccaringuette** [comment]
Fair point.

Rebecca Ringuette

**Comment by asher-pembroke** [comment]
@pythonguru101 develop this on the `plotting` branch. Merge the latest changes from master first.

**Comment by pythonguru101** [comment]
1. Code excerpt in the issue detail page, I tried to run the code but looks like it depends on variable results

`time_date = ts_to_datetime(results['utc_time'])`

I opened the notebook to get the dependent code and I found below imports are present: 

`from kamodo_ccmc.flythrough import SatelliteFlythrough as S
import kamodo_ccmc.flythrough.model_wrapper as MW`

Please tell me from where I can get the kamodo_ccmc module? I tried to run the kamodo-core master branch but it's giving no module found error.

2. For the given code can you please tell me what will be desired output in the plot?

**Comment by rebeccaringuette** [comment]
1. kamodo_ccmc is available at https://github.com/nasa/Kamodo. It takes a few command lines to get it installed, which are described here: https://github.com/nasa/Kamodo/blob/master/Kamodo_CCMC_InstallationInstructions.md
This isn't particularly necessary, through, as the plot results will be the same regardless of the input data. You could just use some sample random arrays of differing numerical scales.
2. The output desired would be something like this if the units are different, but with the function signatures instead of the text axes labels. 
![image](https://user-images.githubusercontent.com/49281118/156030960-b02a4312-b760-421b-a3c7-ceec6e8e2c16.png)
However, if the units of the functions in the plot are the same, then the same vertical axis would be used with all function signatures included in the axis label. 
For four functions with different units, you could try two on each side, one with tick marks in towards the plot and another with tick marks facing out, and with colors associated with the line colors. If that doesn't work, another option is to put three vertical axes on the right side like this:
![image](https://user-images.githubusercontent.com/49281118/156031705-88c41a7a-0c88-4f04-a5ad-91ac867dd8b6.png)

**Comment by asher-pembroke** [comment]
Here's a basic example. `f` should have been plotted on the left vertical axis and `g` should be plotted against the second axis. Subsequent variables should alternate between left and right vertical axes. The same goes for the bottom and top axes

```python
from kamodo import Kamodo
import numpy as np

k = Kamodo()

x_ = np.linspace(-5,5,303)
k['f[kg/m^3]'] = lambda x=x_: x**2-x-1
k['g[g/cm^3]'] = lambda x=x_: np.sin(x)**2
k.plot('f','g')
```
![newplot (6)](https://user-images.githubusercontent.com/13787870/156645018-f7982a88-bc60-430e-b1a2-16dfffdcdeeb.png)

**Comment by pythonguru101** [comment]
I have pushed to plotting branch for issue-35. As requested the f and g are in left and right side in the below plot. One thing I need clarification for this statement additional variables should alternate between left and right.
Can you please give me an example? also please check the below output graph if it looks okay or not
![image](https://user-images.githubusercontent.com/26586879/156890919-a633e750-2b05-4d2a-8893-7afe54feefce.png)
!

**Comment by pythonguru101** [comment]
Could you please share with me some code that has more than 2,3 functions. I want to test with that.
This is how it looks if the number of variables is <=3
<img width="871" alt="image-20220306-212022" src="https://user-images.githubusercontent.com/26586879/157007513-2032c3a4-3b14-43f3-b463-cd66a516a383.png">
If the number of variables is greater than 3 then it will create subplots to make it cleaner.
<img width="967" alt="image-20220306-211326" src="https://user-images.githubusercontent.com/26586879/157007625-c217d057-e949-4a08-a21f-c2aba4034e97.png">

**Comment by rebeccaringuette** [comment]
Thanks, Asher. Also, the multiple sets of horizontal gridlines is
confusing. It may be clearer to just have no horizontal gridlines. It would
be good to see what happens when multiple functions are plotted and have
the same units. (They should share the same vertical axis.)

Rebecca Ringuette

**Comment by asher-pembroke** [comment]
Ok, to summarize

- [ ] Keep all traces on the same figure as per requested behavior
- [ ] Make sure function symbols appear as plot titles
- [ ] When axis units are the same, they should use the same vertical axis. For example:

```python
k = Kamodo()
k['f[kg/m^3]'] = lambda x=x_: x**2-x-1 # shares axis (on the left) with g since it has the same units 
k['g[kg/cm^3]'] = lambda x=x_: np.sin(x)**2 # shares axis with f (on the left) since it has the same units
k['h[g/cm^3]'] = lambda x: x # gets its own axis (on the right) since it has different units 
```

**Comment by asher-pembroke** [comment]
@rebeccaringuette  Ok, I've edited my comment to reflect this

**Comment by pythonguru101** [comment]
1. As requested, I have kept all traces on the same figure as per the requested behavior
2. If units are the same this is how it looks:
<img width="768" alt="image-20220318-125113" src="https://user-images.githubusercontent.com/26586879/159025001-f11c56eb-f697-4afb-b4ae-3a09abf7e695.png">
If units are not the same this multiple axis will be created like this:
<img width="785" alt="image-20220318-125225" src="https://user-images.githubusercontent.com/26586879/159025206-5fe3e34b-7d4f-445d-b451-cb2c04bf0860.png">
3. As requested function symbols appear as plot titles.

**Comment by rebeccaringuette** [comment]
This looks much better! Thanks! Can there be a comma and a space between
the function signatures instead of a vertical line?

Rebecca Ringuette

**Comment by pythonguru101** [comment]
as requested, removed | added  `comma `, pushed to plotting branch

**Comment by asher-pembroke** [comment]
@pythonguru101 there is an issue when I plot only some of the variables

```python
k = Kamodo()

x_ = np.linspace(-5,5,303)
k['f[kg/m^3]'] = lambda x=x_: x**2-x-1
k['g[g/cm^3]'] = lambda x=x_: np.sin(x)**2
k['h[kg/m^3]'] = lambda x=x_: np.sin(x)
k.plot('f', 'g') # raises PlotlyKeyError
```

**Comment by asher-pembroke** [comment]
@iamjavaexpert reassigned to you

**Comment by iamjavaexpert** [comment]
I have resolved this issue in plotting branch. Please let me know after checking.

**Comment by asher-pembroke** [comment]
@iamjavaexpert has the fix been merged to master?

**Comment by iamjavaexpert** [comment]
Yes it is resolved in master branch too.

**Comment by asher-pembroke** [comment]
@iamjavaexpert the multi variable plotting is working in `plotting` branch but not in `master`

**Comment by asher-pembroke** [comment]
Merged with master. However, there appears to be a bug with latex rendering when the same function is referenced twice. This may have been addressed with another PR, so I'll close for now.
