### ISSUE TITLE
`vectorize_function` returns three variables rather than one

### ISSUE THREAD

**Issue by asher-pembroke** [EnsembleGovServices/kamodo-core#43]
@pythonguru101 @iamjavaexpert The master branch has made it so `vectorize_function` returns three variables rather than one:

https://github.com/EnsembleGovServices/kamodo-core/blob/e651f7a0642a655287bd35ea4a29ccd506d69531/kamodo/kamodo.py#L523

This conflicts with the KamodoClient subclass, which just returns the signature the way `vectorize_function` used to:

https://github.com/EnsembleGovServices/kamodo-core/blob/176f10e602c68e554ef0d14d4dd3f7edd873bf90/kamodo/kamodo.py#L1293-L1302

**Refactor the master branch so it keeps the old style.** In general, we should avoid making changes that break subclasses. We want to make it as painless as possible to upgrade to new versions of the base class without having to rewrite subclasses.

_Originally posted by @asher-pembroke in https://github.com/EnsembleGovServices/kamodo-core/issues/30#issuecomment-1035709319_

**Comment by rutesh-inexture** [comment]
I have corrected code for vactorize_function.

**Comment by iamjavaexpert** [comment]
I have resolved the issue. Pushed the latest code to plotting branch.
