### ISSUE TITLE
Incorrect symbol registration

### ISSUE THREAD

**Issue by asher-pembroke** [EnsembleGovServices/kamodo-core#44]
## Describe the bug
Symbols for user-defined argument orderings do not match their function signature

```python
    k = Kamodo()
    k['x(r,theta,phi)'] = 'r*sin(theta)*cos(phi)'
    assert k.x(1, np.pi/2, 0) == 1.0
```
The above assertion  passes, but has the incorrect latex representation:
```python
k.to_latex()
```
<img src="https://render.githubusercontent.com/render/math?math=x{\left(\phi,r,\theta \right)} = r \sin{\left(\theta \right)} \cos{\left(\phi \right)}">

Notice that `lhs` and `symbol` do not match in the signatures dictionary:
```python
k.signatures
```
```console
OrderedDict([('x',
              {'symbol': x(phi, r, theta),
               'units': '',
               'lhs': x(r, theta, phi),
               'rhs': r*sin(theta)*cos(phi),
               'arg_units': {}})])
```

## To Reproduce
```python
def test_symbol_order():
    k = Kamodo()
    k['x(r,theta,phi)'] = 'r*sin(theta)*cos(phi)'
    assert k.x(1, np.pi/2, 0) == 1.0
    print(k.to_latex())
    
    xsymbol = k.signatures['x']['symbol']
    from sympy import Symbol
    for i, _ in enumerate(['r', 'theta', 'phi']):
        assert xsymbol.args[i] == Symbol(_)
    
test_symbol_order()
```

**Comment by asher-pembroke** [comment]
`test_symbol_order` should be added to the tests in `test_kamodo.py`

**Comment by pythonguru101** [comment]
The above one I solved, now lhs and symbol matches in the signatures dictionary. One issue: the test case that was added in this issue, has line xsymbol = spherical.signatures['x']['symbol'], please let me know from where I need to import spherical, else I am getting 

`NameError: name 'spherical' is not defined`

Please let me know, based on that will add the test case in test_kamodo.py file and push the code

**Comment by asher-pembroke** [comment]
@pythonguru101 `spherical` should just be `k` - it was a mistake I made when copying code from another notebook. I've updated the test above to fix.
