### ISSUE TITLE
function assignment changes function's repr_latex method

### ISSUE THREAD

**Issue by asher-pembroke** [EnsembleGovServices/kamodo-core#49]
## Describe the bug
Registering a kamodofied function will change that function's `_repr_latex_` method

## To Reproduce

See PR for test https://github.com/EnsembleGovServices/kamodo-core/pull/65#issuecomment-1067124829

The above test needs to be added `test_kamodo.py` for validation of fixes related to this issue.

**Comment by pythonguru101** [comment]
@asher-pembroke 
Pushed the code in the new branch `issue-49`, changed the test case a little bit, request you to review the test case test_preserve_repr_latex. let me know if the test case looks fine

**Comment by asher-pembroke** [comment]
Your test passes because it does not illustrate the problem. Look at the latex strings produced by my version of the test. It's easier to see if you do this in a jupyter notebook, breaking it up line by line:
```python
k = Kamodo(f='x**2-x-1')
k
```
<img src="https://render.githubusercontent.com/render/math?math=f{\left(x \right)} = x^{2} - x - 1">

The above latex string needs to be preserved. Here's what happens when we register `f` with a new kamodo object, using a new function name `g` :

```python
k2 = Kamodo(g=k.f)
k2
```

<img src="https://render.githubusercontent.com/render/math?math=g{\left(x \right)} = \lambda{\left(x \right)}">

That would be ok as long as only the function in k2 was changed, but k2 actually keeps a reference to the original function and assigns a new _repr_latex_ method to it. If we look at our original `k` object it looks like `f` has been renamed to `g`:

```python
k
```

<img src="https://render.githubusercontent.com/render/math?math=g{\left(x \right)} = \lambda{\left(x \right)}">

This is confusing behaviour.  Note that the signatures and details of `k` are unaffected:
```python
k.signatures
```
```console
OrderedDict([('f',
              {'symbol': f(x),
               'units': '',
               'lhs': f,
               'rhs': x**2 - x - 1,
               'arg_units': {}})])
```
```python
k.detail()
```

  | arg_units | lhs | rhs | symbol | units
-- | -- | -- | -- | -- | --
{} | f | x**2 - x - 1 | f(x) |  

## Proposed solution
When we register a callable function (as opposed to a latex string) we wrap the original function in a new function named after the registration symbol. That way the `_repr_latex_` method gets attached to the outer function, leaving the inner function preserved.

**Comment by pythonguru101** [comment]
@asher-pembroke added changes, used updated `test_preserve_repr_latex` and pushed to `Issue-49` branch
