### ISSUE TITLE
Joss Paper

### ISSUE THREAD

**Issue by samaloney** [EnsembleGovServices/kamodo-core#55]
I was just reviewing the joss paper submission and was wondering if it would be possible to expand on this paragraph?

>Space weather models and data employ a wide variety of specialized formats, data structures, and interfaces tailored for the needs of domain experts. However, this specialization is also an impediment to cross-disciplinary research. For example, data-model comparisons often require knowledge of multiple data structures and observational data formats. Even when mature APIs are available, proficiency in programing languages such as python is necessary before progress may be made. This further complicates the transition from research to operations in space weather forecasting and mitigation, where many disparate data sources and models must be presented together in a clear and actionable manner. Such complexity represents a high barrier to entry when introducing the field of space weather to newcomers at space weather workshops, where much of the student’s time is spent installing and learning how to use prerequisite software. Several attempts have been made to unify all existing space weather resources around common standards, but have met with limited success.

In particular the several examples mentioned be listed with referenced, with code repos, website or publications?

**Comment by asher-pembroke** [comment]
Is this a requirement?

**Comment by asher-pembroke** [comment]
We've expanded on this in the current version of the paper in our discussion of the kameleon predecessor.
