### ISSUE TITLE
sympy link broken in docs

### ISSUE THREAD

**Issue by dstansby** [EnsembleGovServices/kamodo-core#59]
[JOSS requirement]

The sympy link on [this page](https://ensemblegovservices.github.io/kamodo-core/notebooks/Syntax/) is broken - it currently points to https://docs.sympy.org/0.7.0/modules/galgebra/latex_ex/latex_ex.html# which gives me a page not found.

**Comment by asher-pembroke** [comment]
Working on this. The new sympy docs no longer contains a full explanation of how their parser works. The old documentation was much better!

http://horacio9573.no-ip.org/sympy-0.6.6-docs-html/modules/galgebra/latex_ex/latex_ex.html

**Comment by asher-pembroke** [comment]
Fixed the link in the documentation site, added it to the joss branch. Closing for now.

https://ensemblegovservices.github.io/kamodo-core/notebooks/Syntax/
