### ISSUE TITLE
Add a 'partial' keyword to the plotting call to make 2D or 3D plotting of higher dimension datasets simpler.

### ISSUE THREAD

**Issue by rebeccaringuette** [EnsembleGovServices/kamodo-core#6]
One of the complications of plotting 4D (time+space) data in Kamodo is how to plot a 2D slice of a 4D function. I'm having trouble creating a gridified function from sample data, so I'll just use a 4D example generated by the GITM_4Dcdf reader in the CCMC branch. (Link below good for a few weeks. Please download for yourself.)

[https://drive.google.com/file/d/1owXjlOAEbqC3Hmg-2GsHwE72cpB6dHaU/view?usp=sharing](url)

The following code produces a kamodo object using the model reader specified with a sample gridified (and non-gridified) function with time, lon, lat, and radius as the four input parameters:
```py
from kamodo_ccmc.readers.gitm_4Dcdf import MODEL
reader = MODEL()
file_prefix = full_path_to_dir+'/*150317'
kamodo_object = reader(file_prefix, gridded_int=True, variables_requested=['vi_east'])
kamodo_object.vi_east_ijk
```
![image](https://user-images.githubusercontent.com/49281118/139340244-f35f44b6-5a53-4691-a4b2-bdfcaf89f297.png)

The interpolation works as expected with the correct output shape - 
```py
kamodo_object.vi_east_ijk(18.,np.linspace(0.,360.,15),np.linspace(-90.,90.,10),1.06434).shape
```
produces an array of shape (15, 10) -  but the 2D plotting won't work out of the box.

![image](https://user-images.githubusercontent.com/49281118/139340448-ae20db51-f3ba-466c-abbb-41f5b01bd24f.png)

The reader_kplots script (linked below) is an (admittedly clunky) way to get around this using the partial decorator. 

![image](https://user-images.githubusercontent.com/49281118/139340607-12cdba25-3306-42fe-9f57-ecc759abb3a8.png)

[https://github.com/EnsembleGovServices/Kamodo-ccmc-readers/blob/master/kamodo_ccmc/readers/reader_kplots.py](url)

The relevant portion of the code used to generate the plot shown is:
```py
from kamodo import Kamodo, kamodofy, partial
plot_kamodo = Kamodo()
def plot2D_func(t, lon, lat, h):
    @kamodofy(units='m/s', arg_units={'lon':'deg', 'lat':'deg'})
    @partial(time=t,radius=h)
    def pfunc(time, lon, lat, radius):
        return getattr(kamodo_object, 'vi_east_ijk')(time=time,lon=lon,lat=lat,radius=radius)
    
    plot_kamodo['LonLat'] = pfunc  
    return plot_kamodo.plot(LonLat=dict(lat=lat,lon=lon)) 
iplot(plot2D_func(18.,np.linspace(0.,360.,500),np.linspace(-90.,90.,200),1.06434))
```
Other sections of the code address the same problem for regular (non-gridified functions) and correcting some funny behavior when plotting Longitude vs Time or X vs Time plots (note the .T on lines 488, 494, 500, 506, 512, and 737 for this). (Apparently the first two dimensions of a 4D numpy array aren't constructed in the typical way. I don't have experience on what this looks like for higher dimensions arrays, but you have been warned. :) )

The request is to simplify plotting a higher-dimension variable in a 2D or 3D plot by introducing a 'partial' keyword into the kamodo plotting functionality instead of having to jump through the hoops I described. (Or maybe just adding some np.squeeze statements?) I imagine it would work in a method similar to the interpolation call for a gridded variable as pictured towards the top. The trick would be to get this to also work for non-gridified functions. It would be cool for users on the web interface to be able to click the desired dimensions to plot from a drop-down list and enter values for the other dimensions (when presented with a range of acceptable input values) to produce such a plot.

**Comment by asher-pembroke** [comment]
This feature is available with the plot_partial keyword in the next release. We need to update our documentation to reflect https://ensemblegovservices.github.io/kamodo-core/API/#multi-function-plots

**Comment by asher-pembroke** [comment]
#74 has resolved this issue in the `master` branch. Opening new issue for plot_partials documentation
