### ISSUE TITLE
Add refs to previous 

### ISSUE THREAD

**Issue by dstansby** [EnsembleGovServices/kamodo-core#62]
[JOSS requirement]

In the JOSS paper there is the sentence:
> Several attempts have been made to unify all existing space weather resources around common standards, but have met with limited success.

This statement should be backed up with a couple of examples of such previous attempts, ideally with references for readers who want to find out more about previous attempts.

**Comment by samaloney** [comment]
This is the same as #55

**Comment by asher-pembroke** [comment]
We have added a section on our previous work with Kameleon which was an attempt to standardize space weather model output.
