### ISSUE TITLE
Add persistent links to JOSS paper references

### ISSUE THREAD

**Issue by dstansby** [EnsembleGovServices/kamodo-core#63]
[JOSS requirement]
Several of the JOSS paper references are just links to github. Since HTTP links are not permanent (e.g. if github changes name, or doesn't exist in the future) these should be updated to include DOI links to specific software versions that are more permanent.

**Comment by asher-pembroke** [comment]
Can you be more specific? Astropy, PyHC, pysat, plasmapy, all have DOIs.
