### ISSUE TITLE
Add Changelog for new releases

### ISSUE THREAD

**Issue by ensemblegov** [EnsembleGovServices/kamodo-core#75]

**Comment by asher-pembroke** [comment]
Summarize all the issues marked Done for the release milestone. [Create a changelog ](https://keepachangelog.com/en/1.0.0/) with bullet points summarizing all the new features and bug fixes.

**Comment by iamjavaexpert** [comment]
@asher-pembroke should i add the link of each issues in changelog ?

**Comment by asher-pembroke** [comment]
Addressing in #82
