### ISSUE TITLE
3D Multi-variable plotting

### ISSUE THREAD

**Issue by asher-pembroke** [EnsembleGovServices/kamodo-core#78]
## Describe the bug
The new plotting fix for #35 breaks 3D multi-variable plotting

## To Reproduce

```python
from kamodo import Kamodo, kamodofy

def test_multi_variable_3d_plotting():
@kamodofy(units = 'g/cm**3')
def f_LMN(
      x_L = np.linspace(-5, 5, 50), 
      y_M = np.linspace(0, 10, 75), 
      z_N = np.linspace(-20, 20, 100)):
    xx, yy, zz = np.meshgrid(x_L,y_M,z_N, indexing = 'xy')
    return xx + yy + zz

kamodo = Kamodo(f_LMN = f_LMN, g_LMN = f_LMN)
kamodo.plot(f_LMN = dict(z_N = 0), 
                  g_LMN = dict(y_M = 5),
                 )
```

The above test contains a snippet from the `docs/notebooks/Visualization.ipynb` which breaks due to the plotting 1d fix.

### Suggested fix

For 3-d plots, use the old behavior, collecting all traces into the same graph.

**Comment by iamjavaexpert** [comment]
@asher-pembroke  Updated code as per old behaviour and pushed to plotting branch.

**Comment by iamjavaexpert** [comment]
@asher-pembroke  Pushed updated code to plotting branch.
