### ISSUE TITLE
Add rpc tests to pytest suite

### ISSUE THREAD

**Issue by asher-pembroke** [EnsembleGovServices/kamodo-core#81]
[`pytest-asyncio`](https://github.com/pytest-dev/pytest-asyncio) may be used to run asyncio tests within our pytest suite.

0. checkout the `rpc` branch
1. `pip install pytest-asyncio` (this needs to be added to `.github/workflows/kamodo-package.yml`)
2. see example use cases https://tonybaloney.github.io/posts/async-test-patterns-for-pytest-and-unittest.html
3. move the code for both `kamodo/rpc/test_kamodo_rpc_kamodo_client.py` and `kamodo/rpc/test_kamodo_rpc_kamodo_server.py` into `kamodo/test_rpc.py` so that the client/server functionality can be tested automatically. Here is an example that may help https://stackoverflow.com/a/63937972

**Comment by asher-pembroke** [comment]
@iamjavaexpert I found the following test in pycapnp that may help. It runs the server on a separate thread so that it waits for the client. I think the thread closes automatically when the script ends.

```python
import platform
import socket
import threading

import pytest

import capnp

from capnp.lib.capnp import KjException

import test_capability_capnp

def test_using_threads():
    """
    Thread test
    """
    capnp.remove_event_loop(True)
    capnp.create_event_loop(True)

    read, write = socket.socketpair()

    def run_server():
        _ = capnp.TwoPartyServer(write, bootstrap=Server())
        capnp.wait_forever()

    server_thread = threading.Thread(target=run_server)
    server_thread.daemon = True
    server_thread.start()

    client = capnp.TwoPartyClient(read)
    cap = client.bootstrap().cast_as(test_capability_capnp.TestInterface)

    remote = cap.foo(i=5)
    response = remote.wait()

    assert response.x == "125"

```

**Comment by iamjavaexpert** [comment]
@asher-pembroke  test_capability_capnp module is not discoverable in the repo.

**Comment by asher-pembroke** [comment]
test_capability_capnp @iamjavaexpert that is just an example. In our case, we just need to run the kamodo server from a thread. I'll try to give a better example.

**Comment by asher-pembroke** [comment]
Need to run `gen_self_signed_cert.py` as part of the github workflow prior to running the rpc tests. Add this to the documentation for running rpc tests.
