### ISSUE TITLE
Need example for using the gridify decorator

### ISSUE THREAD

**Issue by rebeccaringuette** [EnsembleGovServices/kamodo-core#9]
I have become stumped on how to use the gridify decorator appropriately on a sample user-generated data set (e.g. a function that accepts a 4D trajectory and returns a 4D array). Could an example on how to do this be added to the documentation?

**Comment by asher-pembroke** [comment]
This does not sound like a gridify issue. Gridify would convert a function of one (n,4) variable into one that accepts 4 1-d variables of different lengths. For example,

```python
@gridify(x=np.linspace(-3,3,5),
         y=np.linspace(-5,5,11),
         z=np.linspace(-1,1,33),
         t=np.linspace(0,5,12),
         order='C',
        )
def r(xvec):
    return np.linalg.norm(xvec, axis=-1)
```

This would convert `r(xvec)` to `r(x,y,z,t)` so you can generate slices along different axes:

```python
r(t=3.5) # a volume of shape (5, 11, 33) 
r(t=3.5, x=0) # a plane of shape (11, 33)
```

> a sample user-generated data set (e.g. a function that accepts a 4D trajectory and returns a 4D array)

A "4D trajectory" sounds like you have a sequence of 4D data points. If one of those dimensions is time, then it is more appropriate to describe this as a 3D spatial function of one variable `xvec(t)`.

Can you provide a more concrete example for what the user wants?

**Comment by rebeccaringuette** [comment]
I can get the proper behavior you describe from the gridded interpolator (below), but I can't figure out how to plot this. Maybe that was the original question? It's been a while and my original question was admittedly vague.
'''py
from kamodo import kamodofy, gridify, Kamodo
from scipy.interpolate import RegularGridInterpolator
import numpy as np

#define sample coordinate and data arrays
t, lon, lat, ht = np.linspace(0.,24.,10), np.linspace(0.,360.,20), np.linspace(-90.,90.,50), np.linspace(100.,10000.,250)
variable = np.reshape(np.linspace(0.,2*np.pi,10*20*50*250), (10,20,50,250))

#define and kamodofy interpolating function
rgi = RegularGridInterpolator((t, lon, lat, ht), 
                              variable, bounds_error = False, fill_value=np.NaN) 
@kamodofy(units='m/s', data=variable)
def interpolator(xvec):
    """Interpolates 4d variable without a grid"""
    return rgi(xvec)

#gridify same function
interpolator_grid = kamodofy(gridify(interpolator, time = t, lon=lon, lat = lat,  height = ht), 
                             units='m/s', data=variable, arg_units={'time':'hr','lon':'deg','lat':'deg','height':'km'})

#register in a new kamodo object
kamodo_object = Kamodo()
kamodo_object['v'] = interpolator
kamodo_object['v_ijk'] = interpolator_grid
kamodo_object
'''
output: 
![image](https://user-images.githubusercontent.com/49281118/159783711-81f7b10e-cf99-4e5c-8914-2f9342b8e4b0.png)
'''py
kamodo_object.v_ijk(time=10.,lat=90.).shape  #output: (20, 250)
kamodo_object.plot(v_ijk = {'time':10.,'lat':90.})  #output: not supported: out_dim ('N', 'M'), arg_dims [(1,), ('N',), (1,), ('M',)]
'''
Shouldn't this just be a 2D plot? Is there just an 'np.squeeze' statement missing in the logic somewhere?

**Comment by asher-pembroke** [comment]
Try using the `plot_partial` keyword. It sortof works in the master branch but there is an issue with metadata reassignment (see #73).

```python
from kamodo import kamodofy, gridify, Kamodo
from scipy.interpolate import RegularGridInterpolator
import numpy as np

#define sample coordinate and data arrays
t, lon, lat, ht = np.linspace(0.,24.,10), np.linspace(0.,360.,20), np.linspace(-90.,90.,50), np.linspace(100.,10000.,250)
variable = np.reshape(np.linspace(0.,2 * np.pi,10 * 20 * 50 * 250), (10,20,50,250))

#define and kamodofy interpolating function
rgi = RegularGridInterpolator((t, lon, lat, ht), variable, bounds_error = False, fill_value=np.NaN)

@kamodofy(units='m/s', data=variable)
def interpolator(xvec):
    """Interpolates 4d variable without a grid"""
    return rgi(xvec)

#gridify same function
interpolator_grid = kamodofy(gridify(interpolator, time = t, lon=lon, lat = lat,  height = ht), units='m/s', data=variable, arg_units={'time':'hr','lon':'deg','lat':'deg','height':'km'})

#register in a new kamodo object
kamodo_object = Kamodo()
kamodo_object['v'] = interpolator
kamodo_object['v_ijkl'] = interpolator_grid # renamed to match 4 dimensional structure
kamodo_object

```

The next line is a workaround for #73 

```python
from copy import deepcopy
v_ijkl_meta = deepcopy(kamodo_object.v_ijkl.meta) # needed due to bug in partial #73
kamodo_object.plot('v_ijkl', plot_partial={'v_ijkl': {'time':10.,'lat':90.}}) # generates plot below
```
![newplot (7)](https://user-images.githubusercontent.com/13787870/160182148-ea8ff2e8-ac25-45e1-847e-6f702086df82.png)

However, if we want to make another plot with a different slice, we'll get an error due to #73

```python
kamodo_object.v_ijkl.meta = v_ijkl_meta # reassign meta attribute from deepcopy above
kamodo_object.plot('v_ijkl', plot_partial={'v_ijkl': {'lon':10.,'lat':90.}})
```
![newplot (8)](https://user-images.githubusercontent.com/13787870/160182547-1cf21183-0920-4d4c-9874-9a51e7db740f.png)

**Comment by asher-pembroke** [comment]
#74 seems to have resolved the issue with plot_partials. You no longer need to explicitly copy the metadata.
